name: node ci test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-2016']
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-lastest, windows-2022]
        node-version: [17.x, 18.x]
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: list the directories before the chmod
      run: ls -la

    - name: Set execute permissions for test file
      run: |
        chmod +x sum.test.js
        chmod +x app.js
        chmod +x sum.js
        chmod +x server.js


    - name: list the directories after the chmod
      run: ls -la

    - name: npm install, and test
      run: |
        npm install
        npm test

      env:
        CI: true